name: 

on:
  release:
    types:
      - published

jobs:

  build:

    name: "build webapp"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GITHUB_REF }}

      - run: echo ${{ github.event.release.tag_name }}